config/routes.rb
Projects::Application.routes.draw do
  resources :projects do
    get :like, on: :member
    get :favorites, on: :collection
    resources :comments
  end
  resources :discussions do
    resources :opinions
    get :like, on: :member
    post :flag, on: :member
  end

  root 'projects#index'

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  has_many :opinions, dependent: :destroy

  scope :recent, -> {order("created_at DESC")}
  scope :top_3_likes, -> {order("like_counter DESC").limit(3)}
  scope :top_3_visited, -> {order("hit_count DESC").limit(3)}
  scope :least_3_visited, -> {order("hit_count ASC").limit(3)}
  scope :oldest_3, -> {order("created_at ASC").limit(3)}

  def self.generate_random_discussions(number_of_discussions = 50)
    number_of_discussions.times do
      random_title = (0...rand(60)).map {('a'..'z').to_a[rand(26)]}.join
      Discussion.create(title: random_title, body: "Go Flames Go!! 
        Go Flames Go!! Go Flames Go!!")
    end
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_discussion, only: [:flag, :show, :edit, :update, :like]
  
  def index
    @discussions = Discussion.recent
  end

  def show
    @opinion = Opinion.new
    @discussion.hit_count += 1
    @discussion.save
  end

  def edit
  end

  def new
    @discussion = Discussion.new
  end

  def create
    @discussion = Discussion.new(discussion_params)
    @discussion.save
    redirect_to discussions_path
  end

  def update
    @discussion = Discussion.find(params[:id])
    @discussion.update_attributes(discussion_params)
    redirect_to discussion_url
  end

  def discussion_params
    params.require(:discussion).permit(:title, :body)
  end

  def destroy
    @discussion = Discussion.find(params[:id])
    @discussion.destroy
    redirect_to discussions_path
  end

  def like

    session[:discussion_ids] ||= []

    if session[:discussion_ids].include? params[:id].to_i
      redirect_to @discussion, alert: "Liked already"
    else
      session[:discussion_ids] << @discussion.id
      @discussion.like_counter += 1
      @discussion.save
      redirect_to @discussion, notice: "T. Hanks for liking!"
    
    end
    
  end

  # Build a custom action for discussions controller 
  # with “post” called “flag” and requires an id to be 
  # passed
  def flag
    @discussion = Discussion.find(params[:id])
    @discussion.save
  end

  def set_discussion
    @discussion = Discussion.find(params[:id])
  end

end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_form.html.erb
<%= form_for @discussion do |f| %> 
	
	<div class="form-group">
	<%= f.label :title, "My Discussion" %>
	<%= f.text_field :title, class: "form-control" %>
	</div>
	<br>

	<div class="form-group">
	<%= f.label :body, "Discussion Description" %>
	<%= f.text_area :body, class: "form-control" %>
	<br>
    </div>

	<%= f.submit "Submit", class: "btn btn-primary" %>
	<%= link_to "Back", discussions_path, class: "btn btn-danger" %>

<% end %>

app/views/discussions/edit.html.erb
<h1>Edit Your Discussion</h1>
<%= render "form" %>

app/views/discussions/index.html.erb
<h1>Welcome to My Discussions Page</h1>

<%= link_to "New Discussion", new_discussion_path, class: "btn btn-primary" %>
<%= link_to "Projects Page", projects_path, class: "btn btn-primary" %>
<hr>
<h2>Most Recent Discussions</h2>
<% @discussions.each do |discussion| %>
	<p><%= link_to "#{discussion.id}. #{discussion.title}", discussion %></p>
	
	<p><%= discussion.body %></p>
	<%= link_to "Delete", discussion, method: :delete, data: { confirm: 'Are you sure?' } %>
	<%= link_to "Edit", edit_discussion_path(discussion) %>

	<hr>
<% end %>

app/views/discussions/new.html.erb
<h1>Add a New Discussion</h1>
<%= render "form" %>

app/views/discussions/show.html.erb
<h1><%= @discussion.title %></h1>
<p><%= @discussion.body %></p>
<br>
<p>Likes: <%= @discussion.like_counter %></p>
<p>Hit Count: <%= @discussion.hit_count %></p>
<% if session[:discussion_ids].present? && session[:discussion_ids].include?(@discussion.id) %>
  <%= link_to "Liked", "javascript:void(0)", disabled: "disabled", class: "btn btn-primary" %>
<% else %>
<%= link_to "Like", like_discussion_path(@discussion), class: "btn btn-primary" %>
<% end %>
<% if @opinion.errors.any? %>
  <ul>
    <% @opinion.errors.messages.values.each do |msg| %>
    <li><%= msg.join " " %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for [@discussion, @opinion] do |f| %>
  <div class="form-group">
    <%= f.label :body, "What's Your Opinion?:" %>
    <br>
    <%= f.text_area :body %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

<hr>
<h2>Comments:</h2>
<% @discussion.opinions.each do |opinion| %>
  <%= opinion.body %>
  <hr>
<% end %>
<%= link_to "All Discussions", discussions_path, class: "btn btn-primary" %>