config/routes.rb
Projects::Application.routes.draw do
  resources :projects do
    get :like, on: :member
    get :favorites, on: :collection
    resources :comments
  end
  resources :discussions do
    resources :opinions
    get :like, on: :member
    post :flag, on: :member
  end

  root 'projects#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations, dependent: :destroy
  has_many :projects, through: :categorizations
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  validates_presence_of :title, message: "You have to add a title" 
  validates :title, length: { minimum: 10, too_short: " must have at least 10 characters" }
  validates_presence_of :body, message: "There's nothing in the body of your project"

  scope :by_hit, -> { order("hit_count DESC")}
  scope :by_likes, -> { order("like_counter DESC")}
  scope :newest, -> { order("created_at DESC")}
  scope :limit_3, -> {limit(3)}
  scope :recent, lambda { |x|  order("created_at DESC").limit(x)}
  scope :recent2, proc { |x|  order("created_at DESC").limit(x)} # No error if no Args
  scope :all_but, lambda { |ids| where(["id NOT IN (?)", ids])}
  scope :top, lambda { |x|  order("like_counter DESC").limit(x)}
  scope :create_before, lambda { |x| created_at x}

  before_save :capitalize
  before_save :print_message
  before_create :capitalize_title 

  # Write a method that returns a list of Question records 
  # that has a title size greater than 30 characters

  # solution 1
  def self.long_titled
    long_projects = []
    Project.all.each do |x|
      if x.title.length > 30
      long_projects << x
      end
    end
    long_projects
  end

  # solution 2 - Much better
  def self.long_titled_2
    Project.select.all {|p| p.title.length > 30}
  end

  # Generate 100 random projects with varying title length

  def self.generate_random_projects(number_of_projects = 100)
    number_of_projects.times do
      random_title = (0...rand(60)).map {('a'..'z').to_a[rand(26)]}.join
      Project.create(title: random_title, body: "Go Flames Go!!")
    end
  end

  # Loop through all the questions in the system and build a 
  # hash whose keys are the IDs of the questions and the values is 
  # the length of the titles
  def set_id_length_hash
    new_hash = {}
    Project.all.each do |project|
      new_hash[project.id] = project.title.length
    end
    new_hash
  end

  private

  def capitalize
    self.title.capitalize!
    self.body.capitalize!
  end 

  def print_message
    Rails.logger.info ">>>>>>>>>>>>>"
    Rails.logger.info "Saved"
    Rails.logger.info ">>>>>>>>>>>>>"
  end

  def capitalize_title
    self.title.capitalize!
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :like]

  layout = "discussions"

  def index
    
    # @new_projects = Project.limit(3).order(created_at: :desc)
    @new_projects = Project.newest.limit_3
    @projects = Project.by_hit.all_but(@new_projects.collect(&:id))
  end

  def show
    @comment = Comment.new
    @project.hit_count += 1
    @project.save
  end

  def edit

  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      render :new
    end
  end

  def update
    @project = Project.find(params[:id])
    @project.update_attributes(project_params)
    redirect_to project_url
  end

  def project_params
    params.require(:project).permit([:title, :body, {category_ids: []}])
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  def like

    session[:project_ids] ||= []

    if session[:project_ids].include? params[:id].to_i
      redirect_to @project, alert: "Liked already"
    else
      session[:project_ids] << @project.id
      @project.like_counter += 1
      @project.save
      redirect_to @project, notice: "T. Hanks for liking!"
    
    end
    
  end

  def favorites

  end

  private

  def set_project
    @project = Project.find(params[:id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<% Rails.logger.info @project.inspect %>
<%= form_for @project do |f| %> 
	<% if @project.errors.any? %>
		<ul class="alert_message">
			<% @project.errors.messages.values.each do |message| %>
			
			<li><%= message.join "," %></li>
			<% end %>
		</ul>

	<% end %>
	<div class="form-group">
	<%= f.label :title, "My Project" %>
	<%= f.text_field :title, class: "form-control" %>
	</div>
	<br>
	<% if flash[:alert] %>
                <div class="alert alert-danger"><%= flash[:alert] %></div>
        <% elsif flash[:notice] %>
                <div class="alert alert-success"><%= flash[:notice] %></div>        
        <% end %>

	<div class="form-group">
		<%= f.label :body, "Project Description" %>
		<%= f.text_area :body, class: "form-control" %>
		<br>
   </div>
   <ul>
   	<% Category.all.each do |category| %>
   		<li>
   			<%= hidden_field_tag "project[category_ids][]", nil %>
   			<%= check_box_tag "project[category_ids][]", category.id, @project.categories.include?(category), id: dom_id(category) %>
   			<%= label_tag dom_id(category), category.name %>
   		</li>
   	<% end %>

	<%= f.submit "Submit", class: "btn btn-primary" %>
	<%= link_to "Back", projects_path, class: "btn btn-danger" %>

<% end %>

app/views/projects/edit.html.erb
<h1>Edit Your Project</h1>
<%= render "form" %>

app/views/projects/index.html.erb
<a href="#"><h1>Welcome to My Projects Page</h1></a>
<div class="button-float">
<%= link_to "New Project", new_project_path, class: "btn btn-primary" %>
<%= link_to "Discussions Page", discussions_path, class: "btn btn-primary" %>
</div>
</nav>
<div class = "project_list">
<h2>Most Popular Posts</h2>
<% @projects.each do |project| %>
	<p><%= link_to "#{project.title}", project %></p>
	
	<p><%= project.body %></p>
	<%= link_to "Delete", project, method: :delete, data: { confirm: 'Are you sure?' } %>
	<%= link_to "Edit", edit_project_path(project) %>
  <p>Hit Count: <%= project.hit_count %></p>
  <p>Likes: <%= project.like_counter %></p>
	<hr>
<% end %>
</div>
<div class="new_projects">
<h2>Newest Posts</h2>
<% @new_projects.each do |project| %>
  <p><%= link_to "#{project.title}", project %></p>
  
  <p><%= project.body %></p>
  <%= link_to "Delete", project, method: :delete, data: { confirm: 'Are you sure?' } %>
  <%= link_to "Edit", edit_project_path(project) %>
  <p>Hit Count: <%= project.hit_count %></p>
  <p>Created at: <%= formatted_date project.created_at %></p>
  <hr>
<% end %>
</div>
  

app/views/projects/new.html.erb
<h1>Add a New Project</h1>
<%= render "form" %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<p><%= truncate_string @project.body %></p>
<p>Likes: <%= @project.like_counter %></p>
<p>Hit Count: <%= @project.hit_count %></p>
<%= link_to "Edit Project", edit_project_path(@project), class: "btn btn-default" %>

<% if session[:project_ids].present? && session[:project_ids].include?(@project.id) %>
  <%= link_to "Liked", "javascript:void(0)", disabled: "disabled", class: "btn btn-primary" %>
<% else %>
<%= link_to "Like", like_project_path(@project), class: "btn btn-primary" %>
<% end %>
<hr>
<% if @comment.errors.any? %>
  <ul>
    <% @comment.errors.messages.values.each do |msg| %>
    <li><%= msg.join " " %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for [@project, @comment] do |f| %>
  <div class="form-group">
    <%= f.label :body, "Enter New Comment:" %>
    <br>
    <%= f.text_area :body %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

<hr>
<h2>Comments:</h2>
<% @project.comments.each do |comment| %>
  <%= comment.body %>
  <br>
  <%= link_to "Delete Comment", [@project, comment], method: :delete, data: {confirm: "Are you sure you want to delete this answer?"}, class: "btn btn-danger" %>
  <hr>
<% end %>

<%= link_to "All Projects", projects_path, class: "btn btn-primary" %>
<br>
<br>
<br>